# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Community Schools Playbook
email: info@futureforlearning.org
description: >- # this means to ignore newlines until "baseurl:"
  Americans want, need, and deserve excellent schools for all students. This guide provides tools for advancing Community Schools as a strategy to improve schools, provide more equitable opportunities, and prepare students for success in life and as citizens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #
github_username:  #
twitter:
  card: summary

# Build settings
markdown: kramdown
theme: editorial_jekyll_theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

algolia:
    application_id: 8WARWZ5AA0
    index_name: community-schools-playbook
    routing: true
    search_only_api_key: 01f15495b76fde59269d4c8e0ecab479
    nodes_to_index: 'p,h1,h2,h3,h4,h5,dl,ul,ol,div.box,div.blockquote,div'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Sass building
sass:
    sass_dir: _sass
